### ISSUE TITLE
Errors when launching local web-server

### ISSUE THREAD

**Issue by alejoe91** [flatironinstitute/labbox-ephys#383] opened 2021-02-02 10:51 UTC
Hi Jeremy, 

I'm trying to set up labbox-ephys on my local machine following [these instructions](https://github.com/flatironinstitute/labbox-ephys/blob/master/doc/labbox_ephys_web_server.md).

The kachery-daemon is running (I've used the example yaml you provided - https://gist.githubusercontent.com/magland/9b858ee9dae97db9879826316fa2ba52/raw/kachery-example1.yaml):
![image](https://user-images.githubusercontent.com/17097257/106589649-88aea980-654c-11eb-8b7a-ddcd5c3f70bb.png)

However, when I launch the labbox-ephys webapp with:
```
# On MacOS:
labbox-launcher run magland/labbox-ephys:0.4.11 --docker_run_opts "-p 15310:15310 -p 15308:15308" --kachery $KACHERY_STORAGE_DIR
```

I get the following errors on the terminal (pasting the entire output):
```
RUNNING SHELL SCRIPT: /var/folders/vl/0vmqjsjn0dg8ycnxdx_mqrdw0000gr/T/tmp_shellscript_881y8euz/script.sh
++ id -u
+ USER_ID=504
++ id -u
+ GROUP_ID=504
+ USER_INSIDE_CONTAINER=labbox
+ BASE_IMAGE=magland/labbox-ephys:0.4.11
+ NEW_IMAGE=magland/labbox-ephys-nonroot:0.4.11
+ INJECT_USER_DIR=/Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/labbox_launcher/docker/injectUser
+ docker build -f /Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/labbox_launcher/docker/injectUser/injectUser.Dockerfile -t magland/labbox-ephys-nonroot:0.4.11 --build-arg BASE_IMAGE=magland/labbox-ephys:0.4.11 --build-arg NEW_USER=labbox --build-arg NEW_UID=504 --build-arg NEW_GID=504 /Users/abuccino/anaconda3/envs/si/lib/python3.8/site-packages/labbox_launcher/docker/injectUser
Sending build context to Docker daemon  3.072kB
Step 1/8 : ARG BASE_IMAGE
Step 2/8 : FROM $BASE_IMAGE
 ---> a30dd12f2a6c
Step 3/8 : USER root
 ---> Using cache
 ---> 3c4e96455a4c
Step 4/8 : ARG NEW_USER
 ---> Using cache
 ---> 2105f3acaad3
Step 5/8 : ARG NEW_UID
 ---> Using cache
 ---> 7ba9595450d6
Step 6/8 : ARG NEW_GID
 ---> Using cache
 ---> a26265a89814
Step 7/8 : RUN groupadd --gid ${NEW_GID} ${NEW_USER}     && useradd -s /bin/bash --uid ${NEW_UID} --gid ${NEW_GID} -m ${NEW_USER}     && apt-get update && apt-get install -y sudo     && echo ${NEW_USER} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${NEW_USER}     && chmod 0440 /etc/sudoers.d/${NEW_USER}     && groupadd docker && usermod -aG docker ${NEW_USER} && newgrp docker
 ---> Using cache
 ---> d430161c3ff9
Step 8/8 : USER ${NEW_USER}
 ---> Using cache
 ---> 0e5fbbb3408c
Successfully built 0e5fbbb3408c
Successfully tagged magland/labbox-ephys-nonroot:0.4.11
+ docker run -p 15310:15310 -p 15308:15308 -v /Users/abuccino/Documents/Data/kachery-storage:/Users/abuccino/Documents/Data/kachery-storage -e KACHERY_STORAGE_DIR=/Users/abuccino/Documents/Data/kachery-storage -it magland/labbox-ephys-nonroot:0.4.11
+ '[' -n '' ']'
+ cd /labbox-ephys
+ set +x
+ serve -s build -l 15310
Please wait...
ERROR: Cannot copy to clipboard: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel

   ┌─────────────────────────────────────────────────┐
   │                                                 │
   │   Serving!                                      │
   │                                                 │
   │   - Local:            http://localhost:15310    │
   │   - On Your Network:  http://172.17.0.2:15310   │
   │                                                 │
   └─────────────────────────────────────────────────┘

Please wait...
Please wait...
Please wait...
-----------------------------------------------------
Serving labbox-ephys on port 15310
Point your browser to http://localhost:15310
-----------------------------------------------------
+ exec python -u api.py
h5py version > 2.10.0. Some extractors might not work properly. It is recommended to downgrade to version 2.10.0: 
>>> pip install h5py==2.10.0
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
LABBOX_EPHYS_DEPLOY: None
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
{
    "job_handlers": {
        "default": {
            "type": "local"
        },
        "partition1": {
            "type": "local"
        },
        "partition2": {
            "type": "local"
        },
        "partition3": {
            "type": "local"
        },
        "timeseries": {
            "type": "local"
        }
    }
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fed5c78e1d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=20431): Max retries exceeded with url: /feed/getFeedId (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fed5c78e1d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/labbox-ephys/python/labbox_ephys/api/_session.py", line 47, in _run_worker_session
    WS = WorkerSession(labbox_config=labbox_config)
  File "/labbox-ephys/python/labbox_ephys/api/_workersession.py", line 34, in __init__
    self._default_feed_id = kp.get_feed_id('labbox-ephys-default', create=True)
  File "/usr/local/lib/python3.6/dist-packages/kachery_p2p/__init__.py", line 215, in get_feed_id
    return _get_feed_id(feed_name=feed_name, create=create)
  File "/usr/local/lib/python3.6/dist-packages/kachery_p2p/_feeds.py", line 370, in _get_feed_id
    feedName=feed_name
  File "/usr/local/lib/python3.6/dist-packages/kachery_p2p/_core.py", line 615, in _http_post_json
    req = requests.post(url, json=data)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=20431): Max retries exceeded with url: /feed/getFeedId (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fed5c78e1d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Connection closed.
Error in connection handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/websockets/server.py", line 191, in handler
    await self.ws_handler(self, path)
  File "api.py", line 131, in connection_handler
    session.cleanup()
  File "/labbox-ephys/python/labbox_ephys/api/_session.py", line 18, in cleanup
    self._pipe_to_worker_process.send('exit')
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Task exception was never retrieved
future: <Task finished coro=<outgoing_message_handler() done, defined at api.py:103> exception=EOFError()>
Traceback (most recent call last):
  File "api.py", line 109, in outgoing_message_handler
    messages = session.check_for_outgoing_messages()
  File "/labbox-ephys/python/labbox_ephys/api/_session.py", line 23, in check_for_outgoing_messages
    msg = self._pipe_to_worker_process.recv()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Task exception was never retrieved
future: <Task finished coro=<incoming_message_handler() done, defined at api.py:98> exception=ConnectionClosedError('code = 1006 (connection closed abnormally [internal]), no reason',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "/usr/local/lib/python3.6/dist-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.6/asyncio/streams.py", line 674, in readexactly
    yield from self._wait_for_data('readexactly')
  File "/usr/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
    yield from self._waiter
concurrent.futures._base.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "api.py", line 99, in incoming_message_handler
    async for message in websocket:
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 439, in __aiter__
    yield await self.recv()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

and the webapp shows:
![image](https://user-images.githubusercontent.com/17097257/106590011-f529a880-654c-11eb-929e-8fccf6528e37.png)

Any clue?

Cheers
Alessio

**Comment by magland** [comment] 2021-02-02 12:22
Seems like it is not able to connect to the kachery daemon. I will improve the verbosity and push a new version.

Meanwhile,

@jsoules - Alessio is using a Mac. Could you test out on your macbook and see if things run smoothly?

**Comment by magland** [comment] 2021-02-02 12:49
I think the problem is that we need to expose an additional port.
Here's the Mac launch command to launch the latest version:
```
labbox-launcher run magland/labbox-ephys:0.4.13 --docker_run_opts "-p 15310:15310 -p 15308:15308" --kachery $KACHERY_STORAGE_DIR
```

15310 is where the web pages are served from
15308 is the python api
We also need to expose the port for connecting to the kachery daemon: 20431

```
labbox-launcher run magland/labbox-ephys:0.4.13 --docker_run_opts "-p 15310:15310 -p 15308:15308 -p 20431:20431" --kachery $KACHERY_STORAGE_DIR
```

**Comment by magland** [comment] 2021-02-02 14:03
That last -p solution didn't work. I think I know what needs to be done.

**Comment by magland** [comment] 2021-02-02 20:06
@alejoe91, please try the following:

```
labbox-launcher run magland/labbox-ephys:0.4.14 --docker_run_opts "-p 15308:15308 -p 15309:15309 -p 15310:15310 -e KACHERY_P2P_API_HOST=docker.for.mac.localhost" --kachery $KACHERY_STORAGE_DIR
```

In case you are curious, note the following:
* Updated version of the container to 0.4.14 - which respects the KACHERY_P2P_API_HOST environment variable
* Apparently, using docker.for.mac.localhost in place of localhost is the way to access localhost of the host machine from within a container in mac.
* There are now 3 ports needed to expose 15308, 15309, 15310. These are for http web server, http api server, and websocket server.
```

**Comment by alejoe91** [comment] 2021-02-02 20:44
It works! :) Thanks Jeremy :)

![image](https://user-images.githubusercontent.com/17097257/106659890-9b060300-659f-11eb-9411-ec69400d5a48.png)

**Comment by magland** [comment] 2021-02-03 13:17
Great! I'll close this issue, but open a new one for documenting the updated launch command for mac.

**Closed** 2021-02-03 13:17 UTC
Labels: high
